"""Compatibility shim for Qt resource module.

This allows modules generated by Qt Designer that import ``resources_rc``
from the project root to resolve correctly when the package is executed as a
module (e.g. ``python -m gui``) or when tooling imports ``gui.i18n_support``
without loading the full GUI stack.
"""

from gui.resources_rc import *  # noqa: F401,F403
